project_id = "pjxhbjaqtwjmbqfpurcp"

[functions.sync-booking]
verify_jwt = false

[functions.paypal-payment]
verify_jwt = false

[functions.create-peach-checkout]
verify_jwt = false

[functions.peach-webhook]
verify_jwt = false
